# Generated by Django 3.0.8 on 2020-08-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200827_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
