# Generated by Django 3.0.8 on 2020-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200828_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
